name: Deployment
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - uses: pnpm/action-setup@latest
      - run: pnpm env use --global gallium
      - run: pnpm i
      - run: pnpm lint
