name: Deployment
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@master
        with: 
          version: latest
      - uses: actions/setup-node@master
        with:
          node-version: '16'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm lint
  prettify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@master
        with:
          version: latest
      - uses: actions/setup-node@master
        with:
          node-version: '16'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm prettify
  deploy:
    needs: lint
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@master
        with: 
          version: latest
      - uses: actions/setup-node@master
        with:
          node-version: '16'
          cache: 'pnpm'
      - run: pnpm install --global vercel@latest
      - run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
